cc_library(
  name = "net_utils",
  hdrs = glob(["include/net_utils/**/*.h"]),
  srcs = glob(["src/**/*.cpp", "include/**/*.h"]),
  visibility = ["//visibility:public"],
  includes = ["include"],
  deps = [
    "@micro//lib/microloop:microloop",
  ],
)
