cc_library(
  name = "subscriber",
  srcs = glob(["src/**/*.cpp", "src/**/*.h"]),
  hdrs = glob(["include/**/*.h"]),
  includes = ["include"],
  visibility = ["//visibility:public"],
  deps = [
    "@micro//lib/microloop:microloop",
  ],
)

